@startuml





/' Objects '/

class Adress {
	+Adress(string)
	+Adress()
	+~Adress()
	-adress : string
	+getAdress() : string
	+serialize() : string
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
