@startuml





/' Objects '/

class PickUniqId {
	+{static} uniqSequentialIdForPlayers(GlobalArea*) : string
	+{static} uniqSequentialIdForTeams(GlobalArea*) : string
	+{static} uniqSequentialLincanceIdForPlayers(GlobalArea*) : string
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
