@startuml





/' Objects '/

enum Position {
	Defender
	Forward
	Goalkeeper
	Midfielder
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
