@startuml





/' Objects '/

class TcNo {
	+TcNo()
	+TcNo(long long)
	+TcNo(std::string)
	+~TcNo()
	-validate(std::string) : bool
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
